name: Daily NPM Script

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run npm.sh
      run: bash ./npm.sh

    - name: Commit and push changes
      run: |
        git config user.email "github-actions@users.noreply.github.com"
        git config user.name "GitHub Actions"
        git add .
        git commit -m "Monthly PDF Scraper Update"
        git push
